common:
- 改善が見られない場合、通告無くBANされる可能性があります。
- wikiを確認の上、ルールを守ってプレイしてください。
message:
- - ゲームプレイにおける荒らし・迷惑行為の違反を確認しました。
- - ゲーム内の発言や表現に違反を確認しました。
- - 不正行為を確認しました。
- - サーバーに負荷を与える行為を確認しました。
  - ALL値は200以内にしてください。
- - 整地の心得違反を確認しました。
  - 整地の心得に従い整地してください。
violator:
  Sample: '0'
